name: metric
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - ca-certificates
  - openssl
  - matplotlib
  - certifi
  - tqdm
  - scikit-learn
  - ipykernel
